#!/usr/bin/env nbb
;; scripts/gen-kotoba-port.cljs — write src/association_facts.kotoba from
;; data/datascript-tx.edn.
;;
;;   nbb scripts/gen-kotoba-port.cljs           rewrite the port
;;   nbb scripts/gen-kotoba-port.cljs --check    exit 1 if the port on disk
;;                                               is not what this would write
;;
;; The port's header has always said "GENERATED from data/datascript-tx.edn".
;; Until this script existed that was a description of how someone had once
;; typed it, and the parity suite was the only thing standing between the two
;; copies. Now it is true, and the parity suite checks the generator instead of
;; checking a human -- which is the same assertion for much less of the work.

(ns gen-kotoba-port
  (:require [clojure.edn :as edn]
            [clojure.string :as str]
            ["fs" :as fs]))

(def argv (vec (remove #(str/ends-with? % "gen-kotoba-port.cljs")
                       (drop 2 (js->clj (.-argv js/process))))))
(def check? (some #{"--check"} argv))

(def data-path "data/datascript-tx.edn")
(def out-path "src/association_facts.kotoba")
(def slug "ciu")

(def fields
  "Emitted in this order. `entry-field` is asked by name, so the order is only
   the order of the cond branches, but keeping it fixed keeps the diff of a
   regenerated port readable."
  ["id" "title" "association" "isic" "country" "kind" "url" "url-provenance"
   "source-article" "source-quote" "established-date" "last-revised-date"
   "date-unknown-because" "retrieved-at"])

(defn- field-value [e f]
  (let [v (get e (keyword "association-rule" f))]
    (cond (nil? v) nil (keyword? v) (name v) :else (str v))))

(defn- lit [s]
  (when (str/includes? s "\"")
    (throw (ex-info (str "a double quote in catalog text would need escaping the "
                         "Kotoba subset does not offer: " s) {})))
  (str "\"" s "\""))

(def some- "(option-some-of [:option :string] ")
(def none "(option-none-of [:option :string])")

(defn- entry-fn [i e]
  (str "(defn entry-field-" i " [f :string] [:option :string]\n"
       "  (cond\n"
       (str/join "\n"
                 (for [f fields :let [v (field-value e f)] :when (some? v)]
                   (str "    (string=? f " (lit f) ") " some- (lit v) ")")))
       "\n    :else " none "))\n"))

(defn- dispatch [fname args body-for-i n tail]
  (str "(defn " fname " " args " [:option :string]\n"
       "  (if (valid-entry? a i)\n"
       "    (cond\n"
       (str/join "\n" (for [i (range n)] (str "      (= i " i ") " (body-for-i i))))
       "\n      :else " none ")\n"
       "    " tail "))\n"))

(defn- render [entries]
  (let [n (count entries)
        topics (mapv #(mapv name (:association-rule/topic %)) entries)
        max-topics (apply max 1 (map count topics))]
    (str
     ";; The CIU source catalog, as Kotoba.\n"
     ";;\n"
     ";; GENERATED by scripts/gen-kotoba-port.cljs from data/datascript-tx.edn,\n"
     ";; which src/association/facts.cljc holds as data. Both are the same\n"
     ";; catalog; this one reaches the Kotoba oracle, wasm and both native ISAs,\n"
     ";; which the .cljc cannot. Do not hand-edit -- run the generator, and\n"
     ";; `--check` will tell you if someone did.\n"
     ";;\n"
     ";; `:topic` is a SET in the source. A set has no order and `topic` is\n"
     ";; indexed by position, so the generator uses the order the data file\n"
     ";; writes. `by-topic-id` answers by name and is unaffected.\n"
     ";;\n"
     ";; Parity: test/association_facts_kotoba_parity_test.clj compares every\n"
     ";; field of every entry against the .cljc, so this file cannot drift from\n"
     ";; the data without the suite saying so.\n"
     "\n"
     "(ns association-facts\n"
     "  (:export [main association-covered? entry-count entry-field topic-count\n"
     "            topic by-topic-count by-topic-id coverage-note]))\n"
     "\n"
     "(defn association-covered? [a :string] :bool (string=? a " (lit slug) "))\n"
     "\n"
     "(defn entry-count [a :string] :i64 (if (association-covered? a) " n " 0))\n"
     "\n"
     "(defn valid-entry? [a :string i :i64] :bool\n"
     "  (if (association-covered? a) (if (< i 0) false (< i " n ")) false))\n"
     "\n"
     (str/join "\n" (map-indexed entry-fn entries))
     "\n"
     (dispatch "entry-field" "[a :string i :i64 f :string]"
               #(str "(entry-field-" % " f)") n none)
     "\n"
     "(defn topic-count [a :string i :i64] :i64\n"
     "  (if (valid-entry? a i)\n"
     "    (cond\n"
     (str/join "\n" (for [i (range n)] (str "      (= i " i ") " (count (nth topics i)))))
     "\n      :else 0)\n"
     "    0))\n"
     "\n"
     ;; `topic` is (entry, position) -> name. Emitted position-major so that a
     ;; catalog whose entries carry different topic sets still renders.
     "(defn topic [a :string i :i64 t :i64] [:option :string]\n"
     "  (if (valid-entry? a i)\n"
     "    (cond\n"
     (str/join "\n"
               (for [i (range n)]
                 (str "      (= i " i ") (cond\n"
                      (str/join "\n"
                                (for [[t nm] (map-indexed vector (nth topics i))]
                                  (str "        (= t " t ") " some- (lit nm) ")")))
                      "\n        :else " none ")")))
     "\n      :else " none ")\n"
     "    " none "))\n"
     "\n"
     (let [by-topic (reduce (fn [m [i ts]] (reduce #(update %1 %2 (fnil conj []) i) m ts))
                            {} (map-indexed vector topics))]
       (str
        "(defn by-topic-count [a :string candidate :string] :i64\n"
        "  (if (association-covered? a)\n"
        "    (cond\n"
        (str/join "\n" (for [[t is] (sort-by key by-topic)]
                         (str "      (string=? candidate " (lit t) ") " (count is))))
        "\n      :else 0)\n"
        "    0))\n"
        "\n"
        "(defn by-topic-id [a :string candidate :string i :i64] [:option :string]\n"
        "  (if (association-covered? a)\n"
        "    (cond\n"
        (str/join "\n"
                  (for [[t is] (sort-by key by-topic)]
                    (str "      (string=? candidate " (lit t) ") (cond\n"
                         (str/join "\n"
                                   (for [[pos ei] (map-indexed vector is)]
                                     (str "        (= i " pos ") (entry-field a " ei " \"id\")")))
                         "\n        :else " none ")")))
        "\n      :else " none ")\n"
        "    " none "))\n"))
     "\n"
     "(defn coverage-note [a :string] [:option :string]\n"
     "  (if (association-covered? a)\n"
     "    " some- "\n"
     "      " (lit (str "cloud-itonami-assoc-9411-ury-ciu Wave 0 (ADR-2607141700): "
                        n " ciu entries, each citing a primary source with the "
                        "article and the verbatim span it rests on. Extend the "
                        "sovereign catalog; never fabricate a rule id/url.")) ")\n"
     "    " none "))\n"
     "\n"
     "(defn main [] :i64 0)\n"
     ;; max-topics is computed but unused in the emitted text; naming it here
     ;; keeps the reason visible: the topic renderer is position-major so a
     ;; future entry with two topics needs no change to this generator.
     (do max-topics ""))))

(let [entries (edn/read-string (fs/readFileSync data-path "utf8"))
      _ (when-not (and (vector? entries) (seq entries))
          (println "REFUSED:" data-path "is not a non-empty vector")
          (.exit js/process 2))
      text (render entries)]
  (if check?
    (let [on-disk (try (fs/readFileSync out-path "utf8") (catch :default _ nil))]
      (if (= on-disk text)
        (do (println (str "ok — " out-path " matches the generator ("
                          (count entries) " entries)")) (.exit js/process 0))
        (do (println (str "STALE: " out-path " is not what the generator writes."))
            (println "  run: nbb scripts/gen-kotoba-port.cljs")
            (.exit js/process 1))))
    (do (fs/writeFileSync out-path text)
        (println (str "wrote " out-path " — " (count entries) " entries")))))
